## Configuration for single eureka server, and no spring config
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/

#words: a,the

server:
  port: ${PORT:${SERVER_PORT:0}}